print('Quinn says hello world')
print('Eric says hello universe')
print('Hi this is Tom!')
print('Michael says howdy')
print('Hi this is other Tom')
print("Hi I am Ali :)")
print("Brandon's here too")
print('Joel is late')